# Generated by Django 3.1.1 on 2020-12-14 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfeed',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
