# Generated by Django 3.1.1 on 2020-12-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0002_postfeed_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfeed',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
