# Generated by Django 3.1.1 on 2021-01-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0006_membership_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='joined',
            field=models.DateTimeField(null=True),
        ),
    ]
