# Generated by Django 3.1.1 on 2021-01-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0009_auto_20210108_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='joined_on',
        ),
        migrations.AddField(
            model_name='membership',
            name='joined',
            field=models.DateTimeField(null=True),
        ),
    ]
