# Generated by Django 3.1.1 on 2021-01-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0010_auto_20210108_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='joined',
            field=models.DateField(null=True),
        ),
    ]
