# Generated by Django 3.1.1 on 2021-01-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0011_auto_20210108_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
