# Generated by Django 3.1.1 on 2021-01-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0012_auto_20210108_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='city',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='country',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='state',
        ),
        migrations.AlterField(
            model_name='membership',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
