# Generated by Django 3.1.1 on 2021-01-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0013_auto_20210109_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
