# Generated by Django 3.1.1 on 2021-01-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0014_membership_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='country',
            new_name='location',
        ),
    ]
