# Generated by Django 3.1.1 on 2021-01-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0016_membership_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='joined',
            field=models.DateTimeField(null=True),
        ),
    ]
