# Generated by Django 3.1.1 on 2021-01-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0017_auto_20210109_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='joined',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
