# Generated by Django 3.1.1 on 2021-01-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0018_auto_20210109_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
