# Generated by Django 3.1.1 on 2021-01-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0019_membership_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
        migrations.AddField(
            model_name='postfeed',
            name='click',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='postfeed',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='postfeed',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='postfeed',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='postfeed',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postfeed',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
