# Generated by Django 3.1.1 on 2021-01-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0021_auto_20210115_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfeed',
            name='user_likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='PostFeed',
        ),
    ]
