# Generated by Django 3.1.1 on 2021-01-16 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0023_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
