# Generated by Django 3.1.1 on 2021-01-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI_UX', '0024_post_post_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_data',
            new_name='post_date',
        ),
    ]
